# -*- coding: utf-8 -*-
"""
Created on Sun Apr  9 15:23:13 2023

@author: Admin
"""

data = []

data = [1,2,3]
data = [1,"hello",3,4,3,4,True,"True"]

data1 = [1,2,3,[4,5,'str'],True,"True"]

data = ["physics", 'chemistry', 1997,2000]
new_data=[1,2,3,4]
data[1]
new_data[0:2]
data[-4]
data[-1]
data[:]
data[-2:]
data[1:]
data[-1:-1]
data[:-2]

data1 = [1,2,3,[4,5,"str"],7,8]
data1[3][0]
data1[3][2]="STR"

data = [123, "xyz", "def", "abc"]
data.append(2009)
data.append(data1)
new_data=[1,2,3,4,5]
new_data.extend(data1)


Data = ["physics", "chemestry", 1997,2000]
del Data[0]


























